version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3000:3000"
  database:
    build:
      context: .
      dockerfile: Dockerfile.sql
    env_file:
      - .env
    hostname: sql.projectbot